name: Metrics
on:
  # Schedule updates (each day)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_ignored: html, css, scss, sass, less, shell, batch, powershell, pug
          plugin_languages_limit: 12
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage, lines
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_lines: yes
          plugin_licenses: yes
          plugin_licenses_ratio: yes
          plugin_people: yes
          token: ${{ secrets.METRICS_TOKEN }}
